### ISSUE TITLE
Why minsdk is 17?

### ISSUE THREAD

**Issue by lulumeya** [PierfrancescoSoffritti/AndroidYouTubePlayer#18]
I wonder if there are reasons which need to use sdk over 17?

**Comment by PierfrancescoSoffritti** [comment]
Hi, yes. Is for WebView compatibility. I've found many problems while testing on older versions of Android. API 17 isn't ideal though, there may be problems on some KitKat devices. API 21 is probably the right one, because from there the WebView is updated separately from the OS.
That said, you can try to lower the min sdk, it may or may not work on some devices :)

Anyways I'll probably release an update and increase it to 19 soon. In most cases support for devices from KitKat and above is more than enough.

**Comment by lulumeya** [comment]
Thanks for fast reply. I understand about your concern. I will close this.
