### ISSUE TITLE
remove audio

### ISSUE THREAD

**Issue by jheimes-silveira** [PierfrancescoSoffritti/AndroidYouTubePlayer#36]
Is there any way I can leave the video muted?

**Comment by omi90** [comment]
I don't think there is functionality of mute currently.
But you can always use custom action as below 
`youTubePlayerView.setCustomActionRight(ContextCompat.getDrawable(MainActivity.this, R.drawable.ic_mute_36dp), new View.OnClickListener() {
  @Override
  public void onClick(View view) {
  }
});`
and handle your mute scenario.

**Comment by PierfrancescoSoffritti** [comment]
Hi, there's no such functionality at the moment. The thing is that almost always you want the system to handle the volume, not specific apps, that's the best practice. 

But I understand that for some use cases this may be a useful feature. It is actually pretty easy to implement, you just need to add a method to the player's interface and relative callbacks on the javascript side of the library.

At the moment I am busy studying for job interviews, therefore i don't have time to make changes to the library, but when I ll have a some free time near the end of the year I'd like to rewrite and improve it. This is one of the features I would add.

If you need it now, you are more than welcome to go head and send a pull request :)

I don't think the solution suggested by @omi90 will work, in order to mute the videos you have to call the Javascript method on the player, and this is not possible from outside the library. Or maybe you could do it just by removing all the sounds from your Activity, it's a bit hacky but it could work.

**Comment by PierfrancescoSoffritti** [comment]
Hi, starting from version 0.7.9 is possible to mute/unmute the player.

**Comment by agrvaibhav** [comment]
@PierfrancescoSoffritti Can I show a volume control icon on the player which user can use?

**Comment by PierfrancescoSoffritti** [comment]
[Yes](https://github.com/PierfrancescoSoffritti/android-youtube-player#custom-actions).
